import requests

# print(requests.get('http://localhost:8080/academicSessions/ACAD_SESS_1').json())

# print(requests.get('http://localhost:8080/academicSessions').json())
# print(requests.get('http://localhost:8080/academicSessions/ACAD_SESS_1').json())
# print(requests.get('http://localhost:8080/classes').json())
# print(requests.get('http://localhost:8080/classes/CLASS_001').json())
# print(requests.get('http://localhost:8080/courses').json())
# print(requests.get('http://localhost:8080/courses/COURSE_001').json())
# print(requests.get('http://localhost:8080/gradingPeriods').json())
# print(requests.get('http://localhost:8080/gradingPeriods/ACAD_SESS_3').json())
# print(requests.get('http://localhost:8080/demographics').json())
# print(requests.get('http://localhost:8080/demographics/USER_0').json())
# print(requests.get('http://localhost:8080/enrollments').json())
# print(requests.get('http://localhost:8080/enrollments/ENROLLMENT_001').json())
# print(requests.get('http://localhost:8080/orgs').json())
# print(requests.get('http://localhost:8080/orgs/ORG_1').json())
# print(requests.get('http://localhost:8080/students').json())
# print(requests.get('http://localhost:8080/students/USER_0').json())
# print(requests.get('http://localhost:8080/teachers').json())
# print(requests.get('http://localhost:8080/teachers/USER_0').json())
# print(requests.get('http://localhost:8080/terms').json())
# print(requests.get('http://localhost:8080/terms/ACAD_SESS_2').json())
# print(requests.get('http://localhost:8080/users').json())
# print(requests.get('http://localhost:8080/users/USER_0').json())
# print(requests.get('http://localhost:8080/schools').json())
# print(requests.get('http://localhost:8080/schools/ORG_1').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/courses').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/classes/CLASS_001/enrollments').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/classes/CLASS_001/students').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/classes/CLASS_001/teachers').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/classes/CLASS_001/enrollments').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/students').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/teachers').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/terms').json())
# print(requests.get('http://localhost:8080/terms/ACAD_SESS_2/classes').json())
# print(requests.get('http://localhost:8080/terms/ACAD_SESS_2/gradingPeriods').json())
# print(requests.get('http://localhost:8080/courses/COURSE_001/classes').json())
# print(requests.get('http://localhost:8080/students/USER_0/classes').json())
# print(requests.get('http://localhost:8080/teachers/USER_0/classes').json())
# print(requests.get('http://localhost:8080/schools/ORG_1/classes').json())
# print(requests.get('http://localhost:8080/users/USER_0/classes').json())
# print(requests.get('http://localhost:8080/classes/CLASS_001/students').json())
# print(requests.get('http://localhost:8080/classes/CLASS_001/teachers').json())

# resources checks
print(requests.get('http://localhost:8080/resources').json())
print(requests.get('http://localhost:8080/resources/RESOURCE_001').json())
print(requests.get('http://localhost:8080/courses/COURSE_001/resources').json())
print(requests.get('http://localhost:8080/classes/CLASS_001/resources').json())

# gradebooks checks
print(requests.get('http://localhost:8080/categories').json())
print(requests.get('http://localhost:8080/categories/CAT_001').json())
print(requests.get('http://localhost:8080/lineItems').json())
print(requests.get('http://localhost:8080/lineItems/LI_001').json())
print(requests.get('http://localhost:8080/results').json())
print(requests.get('http://localhost:8080/results/RESULT_001').json())
print(requests.get('http://localhost:8080/classes/CLASS_001/results').json())
print(requests.get('http://localhost:8080/classes/CLASS_001/lineItems').json())
print(requests.get('http://localhost:8080/classes/CLASS_001/lineItems/LI_001/results').json())
print(requests.get('http://localhost:8080/classes/CLASS_001/students/USER_0/results').json())
